env:
  browser: true
  es2021: true
extends:
  - 'eslint:all'
parserOptions:
  ecmaVersion: 12
globals:
  THREE: true
rules:
  # Global settings
  max-len:              [ error, { code: 100, ignoreStrings: true } ]
  strict:               [ error, global ]
  no-use-before-define: [ error, { classes: true, functions: false, variables: false } ]
  quotes:               [ error, single, { allowTemplateLiterals: true } ]
  camelcase:            [ error, { properties: never } ]

  # Disabled
  no-plusplus:            off
  no-magic-numbers:       off
  no-mixed-operators:     off
  no-ternary:             off

  # Disabled but might be interesting
  max-statements:         off
  max-lines-per-function: off
  id-length:              off
  one-var:                off
  prefer-const:           off
  no-param-reassign:      off

  # New lines
  no-multiple-empty-lines:        [ error, { max: 1 } ]
  array-bracket-newline:          [ error, consistent ]
  array-element-newline:          [ error, consistent, { multiline: true } ]
  object-curly-newline:           [ error, { minProperties: 2 } ]
  function-paren-newline:         [ error, consistent ]
  function-call-argument-newline: [ error, consistent ]
  multiline-ternary:              off
  padding-line-between-statements:
    - error
    - { blankLine: always, prev: [ block-like, const, let, directive ], next: '*' }
    - { blankLine: always, prev: '*',                                   next: [ block-like, return ] }
    - { blankLine: any,    prev: [ const, let ],                        next: [ const, let ] }
    - { blankLine: never,  prev: 'return',                              next: '*' }

  # Spaces and indentation
  space-before-blocks:   [ error, always ]
  array-bracket-spacing: [ error, always ]
  object-curly-spacing:  [ error, always ]
  func-call-spacing:     [ error, always ]
  padded-blocks:         [ error, { blocks: never } ]
  indent:                [ error, tab ]
  no-tabs:               [ error, { allowIndentationTabs: true } ]
